// Placeholder — real content is generated by scripts/embed-dist.ts before `bun build --compile`.
// Committing this stub keeps the dev build green even when dist/ is absent.

export function getEmbeddedAsset(_pathname: string): { bytes: Uint8Array; mime: string } | null {
  return null
}

export function getEmbeddedIndex(): { bytes: Uint8Array; mime: string } | null {
  return null
}

export const EMBEDDED_FILE_COUNT = 0
