// Generates server/embedded-dist.ts from the built SPA in ./dist/.
// Called by `bun run build:app` before `bun build --compile` so that the
// compiled binary carries the SPA bundle inside it (no need to ship `dist/`).
//
// The output module exports a function `getAsset(pathname)` returning the
// file contents as Uint8Array + mime, or null if not embedded.

import { readdir, readFile, stat, writeFile, mkdir } from 'node:fs/promises'
import { extname, join, relative, sep } from 'node:path'

const DIST = join(import.meta.dir, '..', 'dist')
const OUT = join(import.meta.dir, '..', 'server', 'embedded-dist.ts')

const MIME: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.mjs': 'application/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.map': 'application/json; charset=utf-8',
  '.txt': 'text/plain; charset=utf-8',
}

function toPosix(p: string) {
  return p.split(sep).join('/')
}

async function walk(dir: string): Promise<string[]> {
  const out: string[] = []
  for (const ent of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, ent.name)
    if (ent.isDirectory()) out.push(...(await walk(full)))
    else if (ent.isFile()) out.push(full)
  }
  return out
}

async function main() {
  try {
    await stat(DIST)
  } catch {
    console.error(`[embed] dist/ not found at ${DIST}. Run 'bun run build' first.`)
    process.exit(1)
  }

  const files = await walk(DIST)
  const entries: string[] = []
  let totalBytes = 0
  for (const abs of files) {
    const rel = '/' + toPosix(relative(DIST, abs))
    const buf = await readFile(abs)
    totalBytes += buf.byteLength
    const b64 = buf.toString('base64')
    const mime = MIME[extname(abs).toLowerCase()] ?? 'application/octet-stream'
    entries.push(`  ${JSON.stringify(rel)}: { mime: ${JSON.stringify(mime)}, b64: ${JSON.stringify(b64)} },`)
  }

  const src = `// Auto-generated by scripts/embed-dist.ts. Do not edit.
// Embeds the built SPA so \`bun build --compile\` produces a self-contained exe.

interface Asset { mime: string; b64: string }

const TABLE: Record<string, Asset> = {
${entries.join('\n')}
}

const cache = new Map<string, { bytes: Uint8Array; mime: string }>()

function decode(b64: string): Uint8Array {
  const bin = atob(b64)
  const out = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i)
  return out
}

export function getEmbeddedAsset(pathname: string): { bytes: Uint8Array; mime: string } | null {
  const key = pathname === '/' || pathname === '' ? '/index.html' : pathname
  const cached = cache.get(key)
  if (cached) return cached
  const a = TABLE[key]
  if (!a) return null
  const v = { bytes: decode(a.b64), mime: a.mime }
  cache.set(key, v)
  return v
}

export function getEmbeddedIndex(): { bytes: Uint8Array; mime: string } | null {
  return getEmbeddedAsset('/index.html')
}

export const EMBEDDED_FILE_COUNT = ${files.length}
`

  await mkdir(join(import.meta.dir, '..', 'server'), { recursive: true })
  await writeFile(OUT, src, 'utf8')
  console.log(`[embed] wrote ${OUT} — ${files.length} files, ${(totalBytes / 1024).toFixed(1)} KiB (pre-base64)`)
}

await main()
